name: Deploy to EC2

on:
  push:
    branches: [master]
  workflow_dispatch:  # Ejecución manual habilitada

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ejecutar despliegue en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/proyecto
            git pull origin master
            
            docker-compose down
            docker-compose up -d
            



