name: Deploy to EC2

on:
  push:
    branches: [master]
  workflow_dispatch:  # Ejecución manual habilitada

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ejecutar despliegue en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/proyecto
            git pull origin master
            
            # Limpiar cache SOAP de AFIP
            echo "Limpiando cache SOAP de AFIP..."
            docker exec lurica-php sh -c "cd /var/www/html && rm -f var/afip/dev/wsdl--*"
            echo "Cache SOAP limpiado exitosamente"
            
            # Limpiar archivos temporales de WSDL
            echo "Limpiando archivos temporales de WSDL..."
            docker exec lurica-php sh -c "cd /var/www/html && rm -f var/afip/dev/tmp.wsdl.*"
            echo "Archivos temporales WSDL limpiados exitosamente"
            
            # Limpiar archivos REQUEST y RESPONSE de AFIP
            echo "Limpiando archivos REQUEST/RESPONSE de AFIP..."
            docker exec lurica-php sh -c "cd /var/www/html && rm -f var/afip/dev/REQUEST-* var/afip/dev/RESPONSE-*"
            echo "Archivos REQUEST/RESPONSE limpiados exitosamente"
            
            # Verificar y ejecutar migraciones pendientes
            echo "Verificando migraciones pendientes..."
            docker exec lurica-php sh -c "cd /var/www/html && php app/vendor/migrate.php --status=all"
            
            # Ejecutar migraciones pendientes si las hay
            echo "Ejecutando migraciones pendientes..."
            docker exec lurica-php sh -c "cd /var/www/html && php app/vendor/migrate.php --run=migration"
            
            cd /home/ubuntu/proyecto/docker
            docker-compose down
            docker-compose up -d
            



